name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: 'https://fake.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript
        run: npm run build

      - name: Type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint
